<div class="row">
	<div class="col-lg-12 quote-container">
		<div class="quote">
			<!-- Quote generated by the script at the end -->
			<p id="text-quote"></p>
			<span id="quote-left" class="fa fa-chevron-left hidden" aria-hidden="true">
			</span> <span id="quote-right"
				class="fa fa-chevron-right" aria-hidden="true"></span>
		</div>
	</div>
</div>